// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI operations (migrate, db push, studio) use a direct, unpooled
    // connection. Falls back to DATABASE_URL when DIRECT_URL isn't set.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
